// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7KmLEqoaAH6pu71DUUyMSgIOKXLu_jok',
    appId: '1:245082840271:web:855389402e8296679d2bba',
    messagingSenderId: '245082840271',
    projectId: 'mad-project-51993',
    authDomain: 'mad-project-51993.firebaseapp.com',
    storageBucket: 'mad-project-51993.appspot.com',
    measurementId: 'G-1F1XJ5EF1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1_XqOEmZdotdHJU2cw6Qs6jQzUXgOeCA',
    appId: '1:245082840271:android:5f4b8b73c5f99bb49d2bba',
    messagingSenderId: '245082840271',
    projectId: 'mad-project-51993',
    storageBucket: 'mad-project-51993.appspot.com',
  );
}
